// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// leadtypes.js
export const FETCH_LEADTYPES_SUCCESS = 'FETCH_LEADTYPES_SUCCESS';
export const FETCH_LEADTYPE_SUCCESS = 'FETCH_LEADTYPE_SUCCESS';
export const UPDATE_LEADTYPE = 'UPDATE_LEADTYPE';
